# Numpy

1. np.array()
2. n.shape
4. n.reshape(r,c) //returns a new array with changed shape
6. n.resize(r,c)  //changes the array and returns None if success
3. np.arrange
5. np.linespace(start, end, number of elements)
7. ones, zeros, eye, diag
8. np.repeat([1,2], 3)
9. vstack([p,p*2]) hstack
10. x.dot(y)  dot product
11. len(x)   gives number of rows
12. x.T
13. dtype 
14. astype

In [3]:
import numpy as np
y = np.array([4, 5, 6])
m = np.array([[7, 8, 9], [10, 11, 12]])
print(y,'\n',m,'\n',m.shape)  #just shape, not shape()

[4 5 6] 
 [[ 7  8  9]
 [10 11 12]] 
 (2, 3)


In [71]:
n = np.arange(0, 30, 2) # 0 to 30, 2 as interval
s = np.arange(13)**2
r = np.arange(10)
n, s, r

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
       dtype=int32),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [5]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [6]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
a=o.resize(3, 3)
print(a)

None


In [29]:
print("ones\n", np.ones((3, 2)))
print("zeros\n", np.zeros((3,2)))
print("eye\n", np.eye(3))
print("diag\n",np.diag(y))  #y is [4,5,6]

print("*3\t",np.array([1, 2, 3] * 3))
print("repeat",np.repeat([1, 2, 3], 3))

ones
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
zeros
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
eye
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diag
 [[4 0 0]
 [0 5 0]
 [0 0 6]]
*3	 [1 2 3 1 2 3 1 2 3]
repeat [1 1 1 2 2 2 3 3 3]


In [33]:
p = np.ones([2, 3], int)
print(p,'\n')
print(np.vstack([p, 2*p]),'\n')
print(np.hstack([p, 2*p]),'\n')

[[1 1 1]
 [1 1 1]] 

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]] 

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]] 



In [35]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [36]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
#same for - * / ** %

[5 7 9]


In [37]:
x.dot(y)

32

In [38]:
len(x)  #gives number of rows

3

In [39]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [40]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [41]:
z.dtype

dtype('int32')

In [42]:
z = z.astype('f')  #casting to float
z.dtype

dtype('float32')

### Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [43]:
a = np.array([-4, -2, 1, 3, 5])

In [62]:
#dir(a)

In [44]:
a.sum()

3

In [45]:
a.max()

5

In [46]:
a.min()

-4

In [47]:
a.mean()

0.6

In [57]:
a.std()  #standard deviation

3.2619012860600183

In [60]:
a.argmax()   #index of maximum

4

In [61]:
a.argmin()

0

### Indexing / Slicing

In [79]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [80]:
s[0], s[4], s[-1],s[1:5],s[-4:]

(0,
 16,
 144,
 array([ 1,  4,  9, 16], dtype=int32),
 array([ 81, 100, 121, 144], dtype=int32))

In [81]:
s[-5::-2]  #array[start:stop:stepsize]

array([64, 36, 16,  4,  0], dtype=int32)

In [91]:
r = np.arange(36)
r.resize((6, 6))
r[2, 2]

14

In [92]:
r[3, 3:6],r[:2, :-1],r[-1, ::2]

(array([21, 22, 23]),
 array([[ 0,  1,  2,  3,  4],
        [ 6,  7,  8,  9, 10]]),
 array([30, 32, 34]))

In [93]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [94]:
r[r > 30] = 30
r   #if bigger than 30, turn to 30

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [95]:
r[r <=30]  #does the same but changes the shape idk

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 30, 30,
       30, 30])

### Copying

In [105]:
#if a slice changes, array changes two
r=np.arange(36)
r.resize((6, 6))

In [106]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [107]:
r2[:] = 0   
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
#so use 
r_copy = r.copy()

### Iterating Over Arrays

In [113]:
test = np.random.randint(0, 10, (4,3))   #array of 4,3  randoms numbers from [0 - 10)
test

array([[1, 2, 1],
       [6, 1, 7],
       [3, 4, 7],
       [7, 2, 7]])

In [119]:
#by row
for r in test:
    print(r)
print('-'*8)#by index
for i in range(len(test)):
    print(test[i])
#by both
for i, row in enumerate(test):
    print('row', i, 'is', row)
print('-'*8)
#iterating two arrays
test2 = test**2
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[1 2 1]
[6 1 7]
[3 4 7]
[7 2 7]
--------
[1 2 1]
[6 1 7]
[3 4 7]
[7 2 7]
row 0 is [1 2 1]
row 1 is [6 1 7]
row 2 is [3 4 7]
row 3 is [7 2 7]
--------
[1 2 1] + [1 4 1] = [2 6 2]
[6 1 7] + [36  1 49] = [42  2 56]
[3 4 7] + [ 9 16 49] = [12 20 56]
[7 2 7] + [49  4 49] = [56  6 56]


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

# PANDAS

### The Series Data Structure

In [3]:
import pandas as pd
pd.Series

pandas.core.series.Series

In [126]:
animals = ['Tiger', 'Bear', 'Moose', None]
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
3     None
dtype: object

In [127]:
numbers = [1, 2, 3, None]
pd.Series(numbers)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [128]:
import numpy as np
np.nan == None

False

In [129]:
np.nan == np.nan

False

In [130]:
np.isnan(np.nan)

True

In [131]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [132]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [133]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [ ]:
# Creating the Series 
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio', 'Moscow']) 
  
# Create the Index 
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5', 'City 6'] 
  
# set the index 
sr.index = index_ 

In [134]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

# Querying a Series

In [4]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [5]:
s.index


Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [6]:
s.iloc[3]

'South Korea'

In [7]:
s.loc['Golf']

'Scotland'

In [8]:
s[3],s["Golf"]

('South Korea', 'Scotland')

In [9]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [10]:
s[0] #This won't call s.iloc[0] as one might expect, it generates an error instead

KeyError: 0

In [11]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [12]:
total = 0
for item in s:
    total+=item
print(total)

324.0


In [13]:
import numpy as np

total = np.sum(s)
print(total)

324.0


In [14]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0    999
1    851
2    761
3    970
4    959
dtype: int32

In [15]:
len(s)

10000

In [148]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

1.26 ms ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [149]:
%%timeit -n 100
summary = np.sum(s)

85.9 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
s = pd.Series([100, 25, 32, 118, 24, 65]) 

In [30]:
s+=2 #adds two to each item in s using broadcasting
s

0    102
1     27
2     34
3    120
4     26
5     67
dtype: int64

In [27]:
dir(s)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__

In [34]:
for label, value in s.iteritems():
    s._set_values(label, value+2)   #note the _ in _set...
s

0    106
1     31
2     38
3    124
4     30
5     71
dtype: int64

In [38]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

784 ms ± 63.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

333 µs ± 37.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s, s.index

(0             1
 1             2
 2             3
 Animal    Bears
 dtype: object,
 Index([0, 1, 2, 'Animal'], dtype='object'))

In [12]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [156]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [157]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [158]:
all_countries

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [159]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

# The DataFrame Data Structure

In [39]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [18]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                      5
Name: Store 2, dtype: object

In [21]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [19]:
df.loc['Store 1']

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [25]:
type(df.loc['Store 1', 'Cost'])

pandas.core.series.Series

In [26]:
df.T

Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5          5

In [27]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [28]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [29]:
df.loc['Store 1']['Cost']  

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [30]:
df.loc[:,['Name', 'Cost']]  #note the syntax

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [31]:
df.drop('Store 1')

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [32]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [33]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [34]:
copy_df.drop?

In [35]:
del copy_df['Name']
copy_df

Item Purchased  Cost
Store 2      Bird Seed   5.0

In [36]:
df['Location'] = None
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  22.5     None
Store 1  Kevyn   Kitty Litter   2.5     None
Store 2  Vinod      Bird Seed   5.0     None

# Dataframe Indexing and Loading

In [ ]:
costs = df['Cost']
costs

In [ ]:
costs+=2
costs

In [ ]:
df

In [ ]:
!cat olympics.csv

In [1]:
df = pd.read_csv('olympics.csv')
df.head()

NameError: name 'pd' is not defined

In [ ]:
df = pd.read_csv('olympics.csv', index_col = 0, skiprows=1)
df.head()

In [ ]:
df.columns

In [ ]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

# Querying a DataFrame

In [ ]:
df['Gold'] > 0

In [ ]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head()

In [ ]:
only_gold['Gold'].count()

In [ ]:
df['Gold'].count()

In [ ]:
only_gold = only_gold.dropna()
only_gold.head()

In [ ]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

In [ ]:
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

In [ ]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

# Indexing Dataframes

In [37]:
df.head()

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  22.5     None
Store 1  Kevyn   Kitty Litter   2.5     None
Store 2  Vinod      Bird Seed   5.0     None

In [38]:
df['country'] = df.index
df = df.set_index('Gold')
df.head()

KeyError: "None of ['Gold'] are in the columns"

In [ ]:
df = df.reset_index()
df.head()

In [ ]:
df = pd.read_csv('census.csv')
df.head()

In [ ]:
df['SUMLEV'].unique()

In [ ]:
df=df[df['SUMLEV'] == 50]
df.head()

In [ ]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [ ]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

In [ ]:
df.loc['Michigan', 'Washtenaw County']

In [ ]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

# Missing values

In [ ]:
df = pd.read_csv('log.csv')
df

In [ ]:
df.fillna?

In [ ]:
df = df.set_index('time')
df = df.sort_index()
df

In [ ]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [ ]:
df = df.fillna(method='ffill')
df.head()

# Merging Dataframes


In [1]:
import pandas as pd

df = pd.DataFrame([{'Name': 'Chris', 'Item Purchased': 'Sponge', 'Cost': 22.50},
                   {'Name': 'Kevyn', 'Item Purchased': 'Kitty Litter', 'Cost': 2.50},
                   {'Name': 'Filip', 'Item Purchased': 'Spoon', 'Cost': 5.00}],
                  index=['Store 1', 'Store 1', 'Store 2'])
df

Cost Item Purchased   Name
Store 1  22.5         Sponge  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0          Spoon  Filip

In [ ]:
df['Date'] = ['December 1', 'January 1', 'mid-May']
df

In [ ]:
df['Delivered'] = True
df

In [ ]:
df['Feedback'] = ['Positive', None, 'Negative']
df

In [ ]:
adf = df.reset_index()
adf['Date'] = pd.Series({0: 'December 1', 2: 'mid-May'})
adf

In [ ]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])
student_df = student_df.set_index('Name')
print(staff_df.head())
print()
print(student_df.head())

In [ ]:
pd.merge(staff_df, student_df, how='outer', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='inner', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='left', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='right', left_index=True, right_index=True)

In [ ]:
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

In [ ]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business', 'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 'Location': '512 Wilson Crescent'}])
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

In [ ]:
staff_df = pd.DataFrame([{'First Name': 'Kelly', 'Last Name': 'Desjardins', 'Role': 'Director of HR'},
                         {'First Name': 'Sally', 'Last Name': 'Brooks', 'Role': 'Course liasion'},
                         {'First Name': 'James', 'Last Name': 'Wilde', 'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James', 'Last Name': 'Hammond', 'School': 'Business'},
                           {'First Name': 'Mike', 'Last Name': 'Smith', 'School': 'Law'},
                           {'First Name': 'Sally', 'Last Name': 'Brooks', 'School': 'Engineering'}])
staff_df
student_df
pd.merge(staff_df, student_df, how='inner', left_on=['First Name','Last Name'], right_on=['First Name','Last Name'])

# Idiomatic Pandas: Making Code Pandorable

In [ ]:
import pandas as pd
df = pd.read_csv('census.csv')
df

In [ ]:
(df.where(df['SUMLEV']==50)
    .dropna()
    .set_index(['STNAME','CTYNAME'])
    .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

In [ ]:
df = df[df['SUMLEV']==50]
df.set_index(['STNAME','CTYNAME'], inplace=True)
df.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

In [ ]:
import numpy as np
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min': np.min(data), 'max': np.max(data)})

In [ ]:
df.apply(min_max, axis=1)

In [ ]:
import numpy as np
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    return row
df.apply(min_max, axis=1)

In [ ]:
rows = ['POPESTIMATE2010',
        'POPESTIMATE2011',
        'POPESTIMATE2012',
        'POPESTIMATE2013',
        'POPESTIMATE2014',
        'POPESTIMATE2015']
df.apply(lambda x: np.max(x[rows]), axis=1)

# Group by

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]
df

In [ ]:
%%timeit -n 10
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME']==state).dropna()['CENSUS2010POP'])
    print('Counties in state ' + state + ' have an average population of ' + str(avg))

In [ ]:
%%timeit -n 10
for group, frame in df.groupby('STNAME'):
    avg = np.average(frame['CENSUS2010POP'])
    print('Counties in state ' + group + ' have an average population of ' + str(avg))

In [ ]:
df.head()

In [ ]:
df = df.set_index('STNAME')

def fun(item):
    if item[0]<'M':
        return 0
    if item[0]<'Q':
        return 1
    return 2

for group, frame in df.groupby(fun):
    print('There are ' + str(len(frame)) + ' records in group ' + str(group) + ' for processing.')


In [ ]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]

In [ ]:
df.groupby('STNAME').agg({'CENSUS2010POP': np.average})

In [ ]:
print(type(df.groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']))
print(type(df.groupby(level=0)['POPESTIMATE2010']))

In [ ]:
(df.set_index('STNAME').groupby(level=0)['CENSUS2010POP']
    .agg({'avg': np.average, 'sum': np.sum}))

In [ ]:
(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']
    .agg({'avg': np.average, 'sum': np.sum}))

In [ ]:
(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']
    .agg({'POPESTIMATE2010': np.average, 'POPESTIMATE2011': np.sum}))

# Scales

In [ ]:
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                  index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'])
df.rename(columns={0: 'Grades'}, inplace=True)
df

In [ ]:
df['Grades'].astype('category').head()

In [ ]:
grades = df['Grades'].astype('category',
                             categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'],
                             ordered=True)
grades.head()

In [ ]:
grades > 'C'

In [ ]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]
df = df.set_index('STNAME').groupby(level=0)['CENSUS2010POP'].agg({'avg': np.average})
pd.cut(df['avg'],10)

# Pivot Tables

In [ ]:
#http://open.canada.ca/data/en/dataset/98f1a129-f628-4ce4-b24d-6f16bf24dd64
df = pd.read_csv('cars.csv')

In [ ]:
df.head()

In [ ]:
df.pivot_table(values='(kW)', index='YEAR', columns='Make', aggfunc=np.mean)

In [ ]:
df.pivot_table(values='(kW)', index='YEAR', columns='Make', aggfunc=[np.mean,np.min], margins=True)

# Date Functionality in Pandas

In [2]:
import pandas as pd
import numpy as np

### Timestamp

In [3]:
pd.Timestamp('9/1/2016 10:05AM')

Timestamp('2016-09-01 10:05:00')

### Period

In [4]:
pd.Period('1/2016')

Period('2016-01', 'M')

In [5]:
pd.Period('3/5/2016')

Period('2016-03-05', 'D')

### DatetimeIndex

In [6]:
t1 = pd.Series(list('abc'), [pd.Timestamp('2016-09-01'), pd.Timestamp('2016-09-02'), pd.Timestamp('2016-09-03')])
t1

2016-09-01    a
2016-09-02    b
2016-09-03    c
dtype: object

In [7]:
type(t1.index)

pandas.tseries.index.DatetimeIndex

### PeriodIndex

In [8]:
t2 = pd.Series(list('def'), [pd.Period('2016-09'), pd.Period('2016-10'), pd.Period('2016-11')])
t2

2016-09    d
2016-10    e
2016-11    f
Freq: M, dtype: object

In [9]:
type(t2.index)

pandas.tseries.period.PeriodIndex

### Converting to Datetime

In [10]:
d1 = ['2 June 2013', 'Aug 29, 2014', '2015-06-26', '7/12/16']
ts3 = pd.DataFrame(np.random.randint(10, 100, (4,2)), index=d1, columns=list('ab'))
ts3

a   b
2 June 2013   16  46
Aug 29, 2014  14  66
2015-06-26    59  99
7/12/16       27  17

In [11]:
ts3.index = pd.to_datetime(ts3.index)
ts3

a   b
2013-06-02  16  46
2014-08-29  14  66
2015-06-26  59  99
2016-07-12  27  17

In [12]:
pd.to_datetime('4.7.12', dayfirst=True)

Timestamp('2012-07-04 00:00:00')

### Timedeltas

In [13]:
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

In [14]:
pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H')

Timestamp('2016-09-14 11:10:00')

### Working with Dates in a Dataframe

In [15]:
dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
dates

DatetimeIndex(['2016-10-02', '2016-10-16', '2016-10-30', '2016-11-13',
               '2016-11-27', '2016-12-11', '2016-12-25', '2017-01-08',
               '2017-01-22'],
              dtype='datetime64[ns]', freq='2W-SUN')

In [16]:
df = pd.DataFrame({'Count 1': 100 + np.random.randint(-5, 10, 9).cumsum(),
                  'Count 2': 120 + np.random.randint(-5, 10, 9)}, index=dates)
df

Count 1  Count 2
2016-10-02      104      125
2016-10-16      109      122
2016-10-30      111      127
2016-11-13      117      126
2016-11-27      114      126
2016-12-11      109      121
2016-12-25      105      126
2017-01-08      105      125
2017-01-22      101      123

In [17]:
df.index.weekday_name

array(['Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday', 'Sunday',
       'Sunday', 'Sunday', 'Sunday'], dtype=object)

In [18]:
df.diff()

Count 1  Count 2
2016-10-02      NaN      NaN
2016-10-16      5.0     -3.0
2016-10-30      2.0      5.0
2016-11-13      6.0     -1.0
2016-11-27     -3.0      0.0
2016-12-11     -5.0     -5.0
2016-12-25     -4.0      5.0
2017-01-08      0.0     -1.0
2017-01-22     -4.0     -2.0

In [19]:
df.resample('M').mean()

Count 1     Count 2
2016-10-31    108.0  124.666667
2016-11-30    115.5  126.000000
2016-12-31    107.0  123.500000
2017-01-31    103.0  124.000000

In [20]:
df['2017']

Count 1  Count 2
2017-01-08      105      125
2017-01-22      101      123

In [21]:
df['2016-12']

Count 1  Count 2
2016-12-11      109      121
2016-12-25      105      126

In [22]:
df['2016-12':]

Count 1  Count 2
2016-12-11      109      121
2016-12-25      105      126
2017-01-08      105      125
2017-01-22      101      123

In [ ]:
df.asfreq('W', method='ffill')

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

df.plot()

# Distributions in Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.binomial(1, 0.5)

In [ ]:
np.random.binomial(1000, 0.5)/1000

In [ ]:
chance_of_tornado = 0.01/100
np.random.binomial(100000, chance_of_tornado)

In [ ]:
chance_of_tornado = 0.01

tornado_events = np.random.binomial(1, chance_of_tornado, 1000000)
    
two_days_in_a_row = 0
for j in range(1,len(tornado_events)-1):
    if tornado_events[j]==1 and tornado_events[j-1]==1:
        two_days_in_a_row+=1

print('{} tornadoes back to back in {} years'.format(two_days_in_a_row, 1000000/365))

In [ ]:
np.random.uniform(0, 1)

In [ ]:
np.random.normal(0.75)

Formula for standard deviation
$$\sqrt{\frac{1}{N} \sum_{i=1}^N (x_i - \overline{x})^2}$$

In [ ]:
distribution = np.random.normal(0.75,size=1000)

np.sqrt(np.sum((np.mean(distribution)-distribution)**2)/len(distribution))

In [ ]:
np.std(distribution)

In [ ]:
import scipy.stats as stats
stats.kurtosis(distribution)

In [ ]:
stats.skew(distribution)

In [ ]:
chi_squared_df2 = np.random.chisquare(2, size=10000)
stats.skew(chi_squared_df2)

In [ ]:
chi_squared_df5 = np.random.chisquare(5, size=10000)
stats.skew(chi_squared_df5)

In [ ]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

output = plt.hist([chi_squared_df2,chi_squared_df5], bins=50, histtype='step', 
                  label=['2 degrees of freedom','5 degrees of freedom'])
plt.legend(loc='upper right')


# Hypothesis Testing

In [ ]:
df = pd.read_csv('grades.csv')

In [ ]:
df.head()

In [ ]:
len(df)

In [ ]:
early = df[df['assignment1_submission'] <= '2015-12-31']
late = df[df['assignment1_submission'] > '2015-12-31']

In [ ]:
early.mean()

In [ ]:
late.mean()

In [ ]:
from scipy import stats
stats.ttest_ind?

In [ ]:
stats.ttest_ind(early['assignment1_grade'], late['assignment1_grade'])

In [ ]:
stats.ttest_ind(early['assignment2_grade'], late['assignment2_grade'])

In [ ]:
stats.ttest_ind(early['assignment3_grade'], late['assignment3_grade'])